
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  namespace: t23
  labels:
    run: service-list
  name: service-list
spec:
  serviceAccountName: api-call
  containers:
  - image: alpine/curl:3.14
    name: service-list
    command: [ 'sh', '-c', 'while true; do curl -s -k -m 5 -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default.svc.cluster.local/api/v1/namespaces/default/services; sleep 10; done' ]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
