apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend
  name: backend
spec:
  containers:
  - image: nginx:1.23.4-alpine
    name: backend
    resources: {}
    env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            key: db-password
            name: db-credentials
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
