apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bus-app
  name: bus-app
spec:
  initContainers:
    - name: configurer
      image: busybox
      volumeMounts:
        - mountPath: /usr/shared/app
          name: emp-v
      command:
        - wget
        - "-O"
        - "/usr/shared/app/config.json"
        - https://raw.githubusercontent.com/bmuschko/ckad-crash-course/master/exercises/07-init-container/app/config/config.json
  containers:
  - image: bmuschko/nodejs-read-config:1.0.0
    name: web
    ports:
      - containerPort: 8080
    volumeMounts:
      - mountPath: /usr/shared/app
        name: emp-v
    resources: {}
  volumes:
    - name: emp-v
      emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
