apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: exced-po
  name: exced-po
spec:
  containers:
  - image: nginx
    name: exced-po
    resources:
      requests:
        memory: 200Mi
        cpu: 1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
