apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world
  name: hello-world
spec:
  containers:
  - image: bmuschko/nodejs-hello-world:1.0.0
    name: hello-world
    ports:
    - containerPort: 3000
    volumeMounts:
    - mountPath: "/var/log"
      name: cache-volume
    resources:
      requests:
        memory: 100m
        cpu: 1
        ephemeral-storage: 1Gi
      limits:
        memory: 500Mi
        ephemeral-storage: 2Gi
  volumes:
      - name: cache-volume
        emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

status: {}
