apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    env: prod
    team: shiny
  annotations:
    contact: "John Doe"
    commit: "2d3mg3"
spec:
  containers:
  - image: nginx
    name: nginx
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
 #   env: prod
    team: legacy
    app: v1.2.4
  annotations:
    contact: "Mary Harris"
spec:
  containers:
  - image: nginx
    name: nginx
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    env: prod
    team: storage
spec:
  containers:
  - image: nginx
    name: nginx
  restartPolicy: Never