apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-security-context
  name: busybox-security-context
spec:
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
  containers:
  - image: busybox:1.28
    name: busybox-security-context
    command: ["sh", "-c", "sleep 1h"]
    volumeMounts:
      - mountPath: "/data/test"
        name: my-v
    securityContext:
      allowPrivilegeEscalation: false
    resources: {}
  volumes:
    - name: my-v
      emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
