apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend
  name: backend
spec:
  containers:
  - image: nginx:1.23.4-alpine
    name: backend
    volumeMounts:
      - mountPath: "/etc/config"
        name: env-config
    resources: {}
    # on cree ici une variable d'env de nom betta dont la valeur est associé à la clé hello du configmap simpleconfig.
    env:
      - name: betta
        valueFrom:
          configMapKeyRef:
            name: simpleconfig
            key: hello
  volumes:
    - name: env-config
      configMap:
        name: app-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
